on: 
  push:
    branches:
      - main
name: ?? Deploy website on push
jobs:
  web-deploy:
    name: ?? Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ?? Get latest code
      uses: actions/checkout@v2
    
    - name: ?? Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 77.75.122.198
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
